### ISSUE TITLE
openrouter API适配和摘要重用

### ISSUE THREAD

**Issue by DSLZL** [tardis-ksh/hexo-ai-summaries#40]
我在使用cloudflare worker+openrouter来使用Deepseek V3 0324来当摘要的模型
worker.js如下
```
const OPENROUTER_API_KEY = 'API-KEY'; // 直接填入 API Key

export default {
  async fetch(request, env, ctx) {
    // 解析请求信息
    const url = new URL(request.url);
    const method = request.method;
    const headers = Object.fromEntries(request.headers);

    // 示例：直接访问 Worker 地址时调用 deepseek 模型
    if (url.pathname === '/') {
      const openrouterUrl = 'https://openrouter.ai/api/v1/chat/completions';
      const requestBody = {
        model: 'deepseek/deepseek-chat-v3-0324:free',
        messages: [{ role: 'user', content: '你好' }],
      };

      const modifiedHeaders = {
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
      };

      const openrouterRequest = new Request(openrouterUrl, {
        method: 'POST',
        headers: modifiedHeaders,
        body: JSON.stringify(requestBody),
      });

      try {
        const response = await fetch(openrouterRequest);
        const responseBody = await response.json();

        // 返回 OpenRouter 的回复
        return new Response(JSON.stringify(responseBody), {
          status: response.status,
          headers: { 'Content-Type': 'application/json' },
        });
      } catch (error) {
        return new Response(`Error: ${error.message}`, { status: 500 });
      }
    }

    // 检查请求来源是否合法（测试时注释掉以下代码块）
    /*
    const origin = headers['origin'];
    if (!ALLOWED_ORIGINS.includes(origin)) {
      return new Response('Forbidden: Invalid origin', { status: 403 });
    }
    */

    // 构造转发到 OpenRouter 的请求
    const openrouterUrl = 'https://openrouter.ai/api/v1' + url.pathname + url.search;
    const modifiedHeaders = {
      ...headers,
      'Authorization': `Bearer ${OPENROUTER_API_KEY}`, // 使用直接定义的 API Key
      'Content-Type': headers['content-type'] || 'application/json',
    };

    // 转发请求到 OpenRouter
    const openrouterRequest = new Request(openrouterUrl, {
      method: method,
      headers: modifiedHeaders,
      body: request.body,
    });

    try {
      const response = await fetch(openrouterRequest);
      const responseBody = await response.text();

      // 返回 OpenRouter 的响应
      return new Response(responseBody, {
        status: response.status,
        headers: response.headers,
      });
    } catch (error) {
      // 处理错误
      return new Response(`Error: ${error.message}`, { status: 500 });
    }
  },
};
```
加了个默认请求当测试用，可以删除的，跨域请求限制也是
这是[openrouter的API调用](https://openrouter.ai/docs/quickstart)文档
然后我在hexo的config.yml配置如下
```
hexo-ai-summaries:
  enable: true
  # only work after this date
  generateAfterDate: 2024/05
  aiSummaryApi: https://example.com/api/v1/chat/completions
  maxToken: 30000
  prompt:
    You are a highly skilled AI trained in language comprehension and summarization. I would like you to read the text delimited by triple quotes and summarize it into a concise abstract paragraph. Aim to retain the most important points, providing a coherent and readable summary that could help a person understand the main points of the discussion without needing to read the entire text. Please avoid unnecessary details or tangential points.
    Only give me the output and nothing else. Do not wrap responses in quotes. Respond in the Chinese language.
  geminiConfig:
    model: deepseek/deepseek-chat-v3-0324:free
    temperature: 0.7
    headers: false
  tagConfig:
    title: .post-title
    content: .post-content
    toc: .toc-content
```
可不可以加上这个的适配或者有其他的方法让插件支持？
以及我看README并没有说到摘要生成后的处理，可能是每次都重新生成，很浪费token和时间，我想能不能再加一个缓存的功能，比如[Mayx的文章](https://mabbs.github.io/2024/07/03/ai-summary.html)就说的很清楚
（PS：说的可能有的牛头不对马嘴的，请见谅，而且肯定有说漏的地方{{{(>_<)}}}）

**Comment by DSLZL** [comment]
差点忘了说，使用这套配置后，点击生成摘要会有一个无文字样式出来，然后就是获取不到就又变成了原按钮

**Comment by Kshao123** [comment]
1. open router 默认返回的就是 openAI 格式，理论是支持的，但调用 API 时可能会遇到拥挤等其他情况时会响应非标字段，导致在 0.x 的版本中报错，目前 1.x 已经修复

2.  1.x 支持非 stream 的 openAI 输入（application/json，0.x 不支持），如你的示例 demo，这也是 _”差点忘了说，使用这套配置后，点击生成摘要会有一个无文字样式出来，然后就是获取不到就又变成了原按钮“_ 的原因

> 在你的示例中，你可以传入 stream 并直接返回 Response，做到 stream 输出（目前是 json 的一口气输出，细节 AI）

3.  插件只根据接口的输入做展示，具体行为需自行在接口中处理，如 **缓存**：https://github.com/Kshao123/Kshao123.github.io/issues/103#issuecomment-2670686427

> 如需客户端缓存，可以通过 customHtml 参数自行处理

**1.x 有 Breaking Changes 升级需注意~**

**Comment by DSLZL** [comment]
谢谢大佬( ͡° ͜ʖ ͡°)✧

**Comment by DSLZL** [comment]
刚刚试了一下，问题还是无输出和按钮变原样，已经通过该issue更新到v1.1.2和根据README更改config
config如下
```
hexo-ai-summaries:
  enable: true
  # only work after this date
  generateAfterDate: 2024/05 # optional
  aiSummaryApi: https://example.com/v1/chat/completions
  maxToken: 30000 # optional
  prompt:
    You are a highly skilled AI trained in language comprehension and summarization. I would like you to read the text delimited by triple quotes and summarize it into a concise abstract paragraph. Aim to retain the most important points, providing a coherent and readable summary that could help a person understand the main points of the discussion without needing to read the entire text. Please avoid unnecessary details or tangential points.
    Only give me the output and nothing else. Do not wrap responses in quotes. Respond in the Chinese language.
  # fetch body
  aiConfig:
    model: deepseek/deepseek-chat-v3-0324:free
    temperature: 0.7 # optional
    stream: false # optional default true
    headers: { 'Content-Type': 'application/json' } # optional, default undefined
  tagConfig: # optional
    title: .post-title
    content: .post-content
    toc: .toc-content
```
cloudflare worker代码同上

**Comment by DSLZL** [comment]
刚刚试了一下，问题还是无输出和按钮变原样，已经通过该issue更新到v1.1.2和根据README更改config
config如下
```
hexo-ai-summaries:
  enable: true
  # only work after this date
  generateAfterDate: 2024/05 # optional
  aiSummaryApi: https://example.com/v1/chat/completions
  maxToken: 30000 # optional
  prompt:
    You are a highly skilled AI trained in language comprehension and summarization. I would like you to read the text delimited by triple quotes and summarize it into a concise abstract paragraph. Aim to retain the most important points, providing a coherent and readable summary that could help a person understand the main points of the discussion without needing to read the entire text. Please avoid unnecessary details or tangential points.
    Only give me the output and nothing else. Do not wrap responses in quotes. Respond in the Chinese language.
  # fetch body
  aiConfig:
    model: deepseek/deepseek-chat-v3-0324:free
    temperature: 0.7 # optional
    stream: false # optional default true
    headers: { 'Content-Type': 'application/json' } # optional, default undefined
  tagConfig: # optional
    title: .post-title
    content: .post-content
    toc: .toc-content
```
cloudflare worker代码同上
（PS：还是说本地环境的问题?我用的是gitpod）

**Comment by DSLZL** [comment]
话说为什么看不到其他的issue

**Comment by Kshao123** [comment]
目前是支持 open router stream 和 非 stream 的返回，你可以在 worker 中直接返回 Response 进行测试

**Comment by DSLZL** [comment]
给我自己蠢到了，大佬能写个配套的教程么？(*꒦ິ⌓꒦ີ)
以及我觉得应该加上一个配置提供商的config选项，这样就不需要再去转化api的格式了

**Comment by Kshao123** [comment]
- 现有模型相关配置如下，但其实大部分使用场景下都是使用其他服务中转 API，理论这些配置基本可有可无，中转时自己携带即可，如同在你的 workers 固定 API-KEY 一样，不对外服务的话，常用的参数可以在 workers 中固定

  ```js
  aiConfig?: {
      model: string;
      temperature?: number;
      headers?: Record<string, string>;
      stream?: boolean;
    };
  ```

- 我使用你提供的代码是可以应用的，理论格式是没问题的，所以你先要确定下 目标 API 是否正常返回，可以使用 curl 或在其他 ai 产品中测试下

```js
const modifiedHeaders = {
  ...headers,
  'Authorization': `Bearer ${OPENROUTER_API_KEY}`, // 使用直接定义的 API Key
  'Content-Type':  'application/json',
};

// 转发请求到 OpenRouter
const openrouterRequest = new Request(openrouterUrl, {
  method: method,
  headers: modifiedHeaders,
  body: {
   // .... 一些参数配置 如 stream
    ....request?.body
  },
});
```


> 如 open route deepseek/deepseek-chat-v3-0324:free 等热门模型在测试时会出现 流式输出时 当前服务出现异常报错等情况，这些都需要自行关注下（插件不展示错误）

> 你可以使用国内的如 [硅基流动](https://cloud.siliconflow.cn/i/BNshEtg0/)、[火山引擎](https://www.volcengine.com/experience/ark?utm_term=202502dsinvite&ac=DSASUQY5&rc=BM9W6UT3) 现在火山每天都送 token 基本也用不完

**Comment by DSLZL** [comment]
我看到你说openrouter ai的api有时确实是会因为莫名其妙的问题导致异常
所以我选择了cloudflare ai（不用硅基流动和火山引擎是因为活动总有结束或者token也会有用完的一天）
然后我又想到了上面提到的Mayx大佬所写的文章，使用cloudflare ai提供的[@cf/qwen/qwen1.5-14b-chat-awq](https://developers.cloudflare.com/workers-ai/models/qwen1.5-14b-chat-awq/)模型
cloudflare worker代码如下：
```
export default {
  async fetch(request, env, ctx) {
    if (request.method !== 'POST') {
      return new Response('Method Not Allowed', { status: 405 });
    }

    const url = new URL(request.url);
    if (url.pathname !== '/v1/chat/completions') {
      return new Response('Not Found', { status: 404 });
    }

    let json;
    try {
      json = await request.json();
    } catch (e) {
      return new Response('Invalid JSON', { status: 400 });
    }

    const messages = json.messages;
    const aiConfig = json.aiConfig || {};
    const promptConfig = json.prompt;

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return new Response('Missing or invalid "messages" in request body', { status: 400 });
    }

    const userContent = messages.map(msg => msg.content).join('\n');
    const finalPrompt = promptConfig ? `${promptConfig}\n\n"""${userContent}"""` : userContent;

    const max_tokens = json.max_tokens || undefined;
    const temperature = aiConfig.temperature || undefined;
    const top_p = aiConfig.top_p || undefined;
    const stream = json.stream !== undefined ? json.stream : true; // 允许客户端控制 stream，默认 true

    try {
      const aiResponseStream = await env.AI.run(
        '@cf/qwen/qwen1.5-14b-chat-awq',
        {
          prompt: finalPrompt,
          max_tokens: max_tokens,
          temperature: temperature,
          top_p: top_p,
          stream: stream, // 传递 stream 参数
        }
      );

      if (stream) {
        // 如果是流式响应，直接返回 aiResponseStream
        return new Response(aiResponseStream, {
          headers: { 'Content-Type': 'text/event-stream' },
        });
      } else {
        // 如果是非流式响应，需要读取整个响应内容并格式化为 OpenAI 格式
        const aiResponse = await readFullResponse(aiResponseStream); // Helper function to read full response

        const openaiResponse = {
          choices: [
            {
              message: {
                role: 'assistant',
                content: aiResponse, // 直接使用读取的响应内容
              },
              finish_reason: 'stop',
              index: 0,
            },
          ],
        };

        return new Response(JSON.stringify(openaiResponse), {
          headers: { 'Content-Type': 'application/json' },
        });
      }

    } catch (aiError) {
      console.error("Cloudflare AI Error:", aiError);
      return new Response('Cloudflare AI Error', { status: 500 });
    }
  },
};

// Helper function to read the full response from a stream (non-streaming mode)
async function readFullResponse(stream) {
  let fullResponse = '';
  const reader = stream.getReader();
  const decoder = new TextDecoder();

  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    fullResponse += decoder.decode(value);
  }
  return fullResponse;
}
```
需要在worker设置中绑定Worker AI，变量名为“AI”
hexo 配置如下：
```
hexo-ai-summaries:
  enable: true
  # only work after this date
  generateAfterDate: 2024/05 # optional
  aiSummaryApi: https://example.com/v1/chat/completions
  maxToken: 30000 # optional
  prompt:
    You are a highly skilled AI trained in language comprehension and summarization. I would like you to read the text delimited by triple quotes and summarize it into a concise abstract paragraph. Aim to retain the most important points, providing a coherent and readable summary that could help a person understand the main points of the discussion without needing to read the entire text. Please avoid unnecessary details or tangential points.
    Only give me the output and nothing else. Do not wrap responses in quotes. Respond in the Chinese language.
  # fetch body
  aiConfig:
    model: any-model-name	// 这当我乱写的吧，我也不知道填什么，只能看看能不能配合上面
    temperature: 0.7 # optional
    stream: true # optional default true
    headers: { 'Content-Type': 'application/json' } # optional, default undefined
  tagConfig: # optional
    title: .post-title
    content: .post-content
    toc: .toc-content
```
于是还是之前的问题，按钮点击出样式，然后变回原样，没说失败，也不能再次点击重试（这个功能总得有吧？）
所以我又来问问该怎么解决了，学学大佬是怎么解决的
顺带一提，因为cloudflare ai有着固定的格式，我觉得吧，可以加一个选择提供商的配置，其他的我不知道，但是比如openai格式的就可以像现在这样，或者如cloudflare就只需要给一个模型名字（不知道为什么还要加@）和个人令牌即可（说的什么玩意，还是看[Cloudflare Docs](https://developers.cloudflare.com/workers-ai/)吧）
